# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBnWMCGTe3gGNZZMwnR-lsmMBaVagvqi
"""

# StaySmart AI - Streamlit App
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

st.set_page_config(page_title="StaySmart AI", layout="wide")

# ================= HEADER =================
st.markdown("""
<div style='background:linear-gradient(135deg,#667eea,#764ba2);
padding:25px;border-radius:10px'>
<h1 style='color:white;'>🚀 StaySmart AI</h1>
<p style='color:#e0e7ff;'>Predictive Talent Analytics for Bharat’s SMEs</p>
</div>
""", unsafe_allow_html=True)

st.markdown("### 📂 Upload Employee CSV")

# ================= FILE UPLOAD =================
uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    st.success("CSV uploaded successfully!")
    st.dataframe(df.head())

    # ================= PREPROCESS =================
    df.columns = df.columns.str.lower().str.replace(" ", "_")

    required_cols = [
        'satisfaction_score','last_hike_months',
        'overtime_hours','engagement_score'
    ]

    for col in required_cols:
        if col not in df.columns:
            df[col] = np.random.randint(1, 10, len(df))

    optional_cols = {
        'age': np.random.randint(22, 55, len(df)),
        'years_at_company': np.random.randint(0, 15, len(df)),
        'salary_lakhs': np.random.uniform(3, 20, len(df)),
        'work_life_balance': np.random.randint(1, 5, len(df))
    }

    for col, values in optional_cols.items():
        if col not in df.columns:
            df[col] = values

    # ================= CREATE TARGET =================
    risk_score = (
        (10 - df['satisfaction_score']) * 0.25 +
        (df['last_hike_months'] / 36) * 10 * 0.2 +
        (df['overtime_hours'] / 80) * 10 * 0.2 +
        (10 - df['engagement_score']) * 0.2 +
        (5 - df['work_life_balance']) * 0.15
    )

    df['left'] = (risk_score > 5.5).astype(int)

    features = [
        'age','years_at_company','satisfaction_score',
        'last_hike_months','overtime_hours',
        'engagement_score','salary_lakhs','work_life_balance'
    ]

    X = df[features]
    y = df['left']

    # ================= MODEL =================
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    df['flight_risk'] = (model.predict_proba(scaler.transform(X))[:,1] * 100).round(0)

    def label_risk(score):
        if score >= 70:
            return "High Risk"
        elif score >= 50:
            return "Medium Risk"
        else:
            return "Low Risk"

    df['risk_category'] = df['flight_risk'].apply(label_risk)

    # ================= METRICS =================
    st.markdown("## 📊 Key Metrics")
    col1, col2, col3 = st.columns(3)

    col1.metric("Total Employees", len(df))
    col2.metric("High Risk Employees", (df['risk_category']=="High Risk").sum())
    col3.metric("Average Risk Score", round(df['flight_risk'].mean(),1))

    # ================= TABLE =================
    st.markdown("## ⚠️ High Risk Employees")
    st.dataframe(
        df[df['risk_category']=="High Risk"]
        .sort_values("flight_risk", ascending=False)
        .head(10)
    )

    # ================= CHART =================
    st.markdown("## 📈 Risk Distribution")
    fig, ax = plt.subplots()
    df['risk_category'].value_counts().plot(kind='bar', ax=ax)
    st.pyplot(fig)

    # ================= DOWNLOAD =================
    st.markdown("## ⬇️ Download Results")
    st.download_button(
        "Download Full Analysis CSV",
        df.to_csv(index=False),
        file_name="staysmart_results.csv"
    )

else:
    st.info("Upload a CSV file to start analysis.")

